# Generated by Django 6.0.6 on 2026-06-18 00:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('peserta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Absensi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('check_in', models.TimeField(blank=True, null=True)),
                ('check_out', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('hadir', 'Hadir'), ('sakit', 'Sakit'), ('izin', 'Izin'), ('alpha', 'Alpha')], default='hadir', max_length=10)),
                ('keterangan', models.TextField(blank=True)),
                ('peserta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peserta.peserta')),
            ],
            options={
                'unique_together': {('peserta', 'tanggal')},
            },
        ),
    ]
