# Generated by Django 6.0.5 on 2026-07-02 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peserta', '0002_peserta_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peserta',
            name='status',
            field=models.CharField(choices=[('terdaftar', 'Terdaftar (Pending)'), ('aktif', 'Aktif'), ('ditolak', 'Ditolak'), ('selesai', 'Selesai')], default='terdaftar', max_length=10),
        ),
    ]
