# Generated by Django 6.0.5 on 2026-07-02 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peserta', '0003_alter_peserta_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peserta',
            name='bidang_penempatan',
            field=models.CharField(choices=[('Sekretariat', 'Sekretariat'), ('IKP', 'Informasi & Komunikasi Publik (IKP)'), ('Aptika', 'Aplikasi & Informatika (Aptika)'), ('Persandian', 'Persandian & Statistik'), ('IT', 'IT Support / Infrastruktur'), ('Humas', 'Humas & Protokol')], max_length=50),
        ),
    ]
