# Generated by Django 6.0.5 on 2026-07-02 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorprofile',
            name='bidang',
            field=models.CharField(blank=True, choices=[('Sekretariat', 'Sekretariat'), ('IKP', 'Informasi & Komunikasi Publik (IKP)'), ('Aptika', 'Aplikasi & Informatika (Aptika)'), ('Persandian', 'Persandian & Statistik'), ('IT', 'IT Support / Infrastruktur'), ('Humas', 'Humas & Protokol')], max_length=50),
        ),
    ]
