# Generated by Django 6.0.6 on 2026-06-17 15:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('peserta', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Penilaian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kedisiplinan', models.IntegerField()),
                ('kreativitas', models.IntegerField()),
                ('komunikasi', models.IntegerField()),
                ('teknis', models.IntegerField()),
                ('presensi', models.IntegerField()),
                ('presentasi', models.IntegerField()),
                ('sikap', models.IntegerField()),
                ('total_nilai', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('catatan', models.TextField(blank=True)),
                ('tanggal_penilaian', models.DateTimeField(auto_now_add=True)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('peserta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peserta.peserta')),
            ],
        ),
    ]
