# Generated by Django 6.0.5 on 2026-07-02 02:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('peserta', '0004_alter_peserta_bidang_penempatan'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjekMagang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('penjelasan', models.TextField(help_text='Penjelasan detail tentang projek')),
                ('alur_projek', models.TextField(help_text='Alur atau langkah-langkah pengerjaan projek')),
                ('link_repo', models.URLField(blank=True, help_text='Link Repository (GitHub/GitLab)', max_length=500, null=True)),
                ('link_demo', models.URLField(blank=True, help_text='Link Demo/Live Projek', max_length=500, null=True)),
                ('file_dokumen', models.FileField(blank=True, help_text='Dokumen teknis projek', null=True, upload_to='projek_docs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('peserta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='projek', to='peserta.peserta')),
            ],
            options={
                'verbose_name': 'Projek Magang',
                'verbose_name_plural': 'Projek Magang',
            },
        ),
    ]
