# Generated by Django 6.0.6 on 2026-06-17 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('peserta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(auto_now_add=True)),
                ('kegiatan', models.TextField()),
                ('dokumentasi', models.FileField(blank=True, null=True, upload_to='logbook/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('peserta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peserta.peserta')),
            ],
        ),
    ]
