# Generated by Django 6.0.6 on 2026-06-18 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logbook',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('dikirim', 'Dikirim'), ('diverifikasi', 'Diverifikasi')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='logbook',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
