# Generated by Django 6.0.5 on 2026-07-02 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0002_logbook_status_logbook_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='logbook',
            name='catatan_mentor',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='logbook',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('dikirim', 'Dikirim'), ('diverifikasi', 'Diverifikasi'), ('perlu_revisi', 'Perlu Revisi')], default='draft', max_length=20),
        ),
    ]
