# Generated by Django 6.0.6 on 2026-07-16 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0003_logbook_catatan_mentor_alter_logbook_status'),
        ('tugas', '0003_tugas_link_tugas'),
    ]

    operations = [
        migrations.AddField(
            model_name='logbook',
            name='tugas_terkait',
            field=models.ForeignKey(blank=True, help_text='Tugas atau Projek yang berkaitan dengan logbook ini', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logbooks', to='tugas.tugas'),
        ),
    ]
