# Generated by Django 6.0.5 on 2026-07-02 02:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('peserta', '0003_alter_peserta_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tugas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('deskripsi', models.TextField()),
                ('deadline', models.DateField()),
                ('status', models.CharField(choices=[('belum', 'Belum Selesai'), ('selesai', 'Selesai')], default='belum', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tugas_dibuat', to=settings.AUTH_USER_MODEL)),
                ('peserta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tugas_saya', to='peserta.peserta')),
            ],
        ),
    ]
