# Generated by Django 6.0.5 on 2026-07-02 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tugas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tugas',
            name='catatan_mentor',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tugas',
            name='file_tugas',
            field=models.FileField(blank=True, null=True, upload_to='tugas_submisi/'),
        ),
        migrations.AddField(
            model_name='tugas',
            name='nilai',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tugas',
            name='status',
            field=models.CharField(choices=[('belum', 'Belum Dikerjakan'), ('dikirim', 'Menunggu Penilaian'), ('perlu_revisi', 'Perlu Revisi'), ('selesai', 'Selesai (Dinilai)')], default='belum', max_length=15),
        ),
    ]
