# Generated by Django 6.0.5 on 2026-07-02 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tugas', '0002_tugas_catatan_mentor_tugas_file_tugas_tugas_nilai_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tugas',
            name='link_tugas',
            field=models.URLField(blank=True, help_text='Link contoh: GitHub, Google Drive, atau Vercel', max_length=500, null=True),
        ),
    ]
