# Generated by Django 6.0.6 on 2026-07-16 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tugas', '0003_tugas_link_tugas'),
    ]

    operations = [
        migrations.AddField(
            model_name='tugas',
            name='bentuk_projek',
            field=models.CharField(blank=True, help_text='Contoh: Website, Makalah, Desain UI, dll', max_length=200, null=True),
        ),
    ]
