# Generated by Django 6.0.6 on 2026-07-16 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tugas', '0004_tugas_bentuk_projek'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tugas',
            name='status',
            field=models.CharField(choices=[('belum', 'Belum Dikerjakan'), ('proses', 'Sedang Dikerjakan'), ('dikirim', 'Menunggu Penilaian'), ('perlu_revisi', 'Perlu Revisi'), ('selesai', 'Selesai (Dinilai)')], default='belum', max_length=15),
        ),
    ]
